version: "3.9"
   
services:
  db:
    image: postgres:14-alpine
    hostname: postgres
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432


  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      WAIT_HOSTS: db:5432
    links:
      - db
    depends_on:
      - db



volumes:
  net:
  data: null