# Generated by Django 4.0.2 on 2022-02-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Номер пользователя:')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('date', models.CharField(max_length=64, verbose_name='Дата создания:')),
            ],
        ),
    ]
